# dev
version: '3.7'

services:
  webapp-prod:
    container_name: webapp-prod
    build:
      context: ./
      dockerfile: docker/prod/Dockerfile
    ports:
      - "8181:80"
    environment:
      - CHOKIDAR_USEPOLLING=true

