# dev
version: '3.7'

services:
  webapp:
    container_name: webapp
    build:
      context: ./
      dockerfile: docker/dev/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3999:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
