name: Coverage

on:
  pull_request:
    branches: 
      - "**"

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '16' ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install
      run: yarn install
    
    - name: Coverage
      run: yarn run coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}